DEBUG  = 0

USER_AGENT = 'RedditBot Framework Pre-Alpha by /u/EndeRDIT'
SUBREDDIT = 'dota2'
SUBMISSION_LIMIT = 1
COMMENT_LIMIT = 5

SUBMISSIONS_ENABLED = 0
COMMENTS_ENABLED = 1

PLUGIN_LOCATION = 'plugins'
CONFIG_LOCATION = 'config'

